In [2]:
##Import Numpy Library to Jupyter Notebook
import numpy as np

In [3]:
##Numpy Version
np.__version__

'1.19.5'

In [4]:
##Import Pandas Library to Jupyter Notebook
import pandas as pd

In [5]:
##Panda Version
pd.__version__

'1.3.2'

In [13]:
#Load Dataset to df1
df1 = pd. read_csv(R"https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv", index_col = 0)

In [14]:
#Explore Dataset df1
df1

,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
Make,,,,,,,,,,,,,,,
BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [16]:
##Explore headers of Dataset df1
df1.head()

,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
Make,,,,,,,,,,,,,,,
BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [17]:
##Explore number of columns and rows of Dataset df1
df1.shape

(11914, 15)

In [21]:
##Filter Dataset to Only BMW Vehicles to a new Dataset named df2
df2 = df1.loc["BMW"]

In [22]:
##Calculate mean value of df1
df2["MSRP"].mean()

61546.76347305389

In [35]:
##Filter Dataset having year greater or equal to 2015 to a new Dataset named df3
df_mask = df1["Year"] >= 2015
positions = np.flatnonzero(df_mask)
df3=df1.iloc[positions]
df3

,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
Make,,,,,,,,,,,,,,,
FIAT,124 Spider,2017,premium unleaded (recommended),160.0,4.0,MANUAL,rear wheel drive,2.0,Performance,Compact,Convertible,35,26,819,27495
FIAT,124 Spider,2017,premium unleaded (recommended),160.0,4.0,MANUAL,rear wheel drive,2.0,Performance,Compact,Convertible,35,26,819,24995
FIAT,124 Spider,2017,premium unleaded (recommended),160.0,4.0,MANUAL,rear wheel drive,2.0,Performance,Compact,Convertible,35,26,819,28195
BMW,2 Series,2016,premium unleaded (required),240.0,4.0,AUTOMATIC,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,35,23,3916,32850
BMW,2 Series,2016,premium unleaded (required),240.0,4.0,AUTOMATIC,rear wheel drive,2.0,Luxury,Compact,Convertible,34,23,3916,38650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BMW,Z4,2015,premium unleaded (required),300.0,6.0,AUTOMATED_MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Convertible,24,17,3916,56950
BMW,Z4,2015,premium unleaded (required),335.0,6.0,AUTOMATED_MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Convertible,24,17,3916,65800
BMW,Z4,2016,premium unleaded (required),300.0,6.0,AUTOMATED_MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Convertible,24,17,3916,57500
BMW,Z4,2016,premium unleaded (required),240.0,4.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,34,22,3916,49700
BMW,Z4,2016,premium unleaded (required),335.0,6.0,AUTOMATED_MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Convertible,24,17,3916,66350

In [41]:
##Verify years of the new Dataset df3
uniquedf = df3['Year'].unique()
print(sorted(uniquedf))

[2015, 2016, 2017]

In [42]:
##Number of rows that has Engine HP as Null Value
sum(pd.isnull(df3['Engine HP']))

51

In [44]:
##Calculate Mean Value of Engine HP with Null Values
mean_hp_before = df3["Engine HP"].mean()
mean_hp_before

272.98771870794076

In [61]:
##Replace Null Values
df3["Engine HP"].fillna(value=0, inplace=True)

In [62]:
##Calculate new mean value
mean_hp_after = df3["Engine HP"].mean()
mean_hp_after

270.665387823186

In [63]:
##Compare both mean values
print(round(mean_hp_before))
print(round(mean_hp_after))

273
271

In [65]:
##Filter Dataset to Only Rolls Royce and 3 columns to a new Dataset named df5
df5 = df1.loc["Rolls-Royce"]
df5 = df5[["Engine HP", "Engine Cylinders", "highway MPG"]]
df5

             Engine HP  Engine Cylinders  highway MPG
Make
Rolls-Royce      325.0               8.0           15
Rolls-Royce      563.0              12.0           19
Rolls-Royce      563.0              12.0           21
Rolls-Royce      563.0              12.0           21
Rolls-Royce      563.0              12.0           21
Rolls-Royce      563.0              12.0           21
Rolls-Royce      563.0              12.0           20
Rolls-Royce      563.0              12.0           20
Rolls-Royce      563.0              12.0           21
Rolls-Royce      563.0              12.0           21
Rolls-Royce      563.0              12.0           21
Rolls-Royce      563.0              12.0           21
Rolls-Royce      322.0              12.0           15
Rolls-Royce      322.0              12.0           15
Rolls-Royce      453.0              12.0           19
Rolls-Royce      453.0              12.0           19
Rolls-Royce      453.0              12.0           19
Rolls-Royce      453.0              12.0           19
Rolls-Royce      453.0              12.0           19
Rolls-Royce      453.0              12.0           19
Rolls-Royce      453.0              12.0           19
Rolls-Royce      453.0              12.0           19
Rolls-Royce      453.0              12.0           19
Rolls-Royce      453.0              12.0           19
Rolls-Royce      453.0              12.0           19
Rolls-Royce      453.0              12.0           19
Rolls-Royce      322.0              12.0           15
Rolls-Royce      322.0              12.0           15
Rolls-Royce      624.0              12.0           21
Rolls-Royce      624.0              12.0           21
Rolls-Royce      624.0              12.0           21

In [124]:
#Delete duplicates
df5 = df5.drop_duplicates()
df5

             Engine HP  Engine Cylinders  highway MPG
Make
Rolls-Royce      325.0               8.0           15
Rolls-Royce      563.0              12.0           19
Rolls-Royce      563.0              12.0           21
Rolls-Royce      563.0              12.0           20
Rolls-Royce      322.0              12.0           15
Rolls-Royce      453.0              12.0           19
Rolls-Royce      624.0              12.0           21

In [125]:
#Get the underlying NumPy array
x = pd.DataFrame(df5).to_numpy()
x

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [126]:
#t = np.transpose(x).reshape(7,3)
t = np.transpose(x)
t

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [177]:
###Multiply both arrays
x = np.arange(21).reshape(3,7)
t = np.arange(21).reshape(7,3)
xtx = np.matmul(x,t)
#xtx = x * t

In [178]:
#Create Matrix Inverse
inverse = np.linalg.inv(xtx)
inverse

array([[ 4.39804651e+12, -8.79609302e+12,  4.39804651e+12],
       [-8.79609302e+12,  1.75921860e+13, -8.79609302e+12],
       [ 4.39804651e+12, -8.79609302e+12,  4.39804651e+12]])

In [179]:
#Sum of Inverse Matrix
np.sum(inverse)

0.0107421875

In [186]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [181]:
x
x.transpose()

array([[ 0,  7, 14],
       [ 1,  8, 15],
       [ 2,  9, 16],
       [ 3, 10, 17],
       [ 4, 11, 18],
       [ 5, 12, 19],
       [ 6, 13, 20]])

In [182]:
inverse

array([[ 4.39804651e+12, -8.79609302e+12,  4.39804651e+12],
       [-8.79609302e+12,  1.75921860e+13, -8.79609302e+12],
       [ 4.39804651e+12, -8.79609302e+12,  4.39804651e+12]])

In [188]:
#Multiply both arrays
inverse = np.arange(9).reshape(3,3)
transpose = x.transpose()
x = np.arange(21).reshape(7,3)
val1 = np.matmul(x,inverse)
val1

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111],
       [ 96, 126, 156],
       [123, 162, 201],
       [150, 198, 246],
       [177, 234, 291]])

In [190]:
w = y.dot(val1)
w

array([ 719100,  944100, 1169100])

In [191]:
sumw = np.sum(w)
sumw

2832300